spring.application.name=digital-prescription-platform
spring.datasource.url=jdbc:postgresql://root:nBtJTZLbGnuhOItVCmLsNC2Sfuh6d3uu@dpg-d8csg1gg4nts73da0bj0-a.oregon-postgres.render.com/prescription_db_9cle
spring.datasource.username=root
spring.datasource.password=nBtJTZLbGnuhOItVCmLsNC2Sfuh6d3uu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
